services:
  app:
    build: .
    command: node server.js
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
